name = "lottsanook-cfworker"
type = "webpack"
main = "index.js"
account_id = '2d33facc9cdbb91215d1312e5e4d54fe'
usage_model = "bundled"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true
compatibility_date = "2024-09-23"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true